name: Build JNI Library for Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Android NDK r21e
      run: |
        $url = "https://dl.google.com/android/repository/android-ndk-r21e-windows-x86_64.zip"
        $output = "android-ndk.zip"
        Invoke-WebRequest -Uri $url -OutFile $output
        Expand-Archive -Path $output -DestinationPath .
      shell: pwsh

    - name: Set up NDK environment
      run: |
        $ndkPath = "${{ github.workspace }}\android-ndk-r21e"
        echo "NDK_HOME=$ndkPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "NDK_ROOT=$ndkPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "$ndkPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh

    - name: Build with ndk-build
      run: |
        cd jni
        ndk-build NDK_PROJECT_PATH=.
      shell: cmd

    - name: List output files
      run: |
        dir /s *.so
      shell: cmd

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-libraries
        path: ./jni/libs/**/*.so
